#!/usr/bin/perl

use strict;

my $detail = $ENV{'LOGWATCH_DETAIL_LEVEL'} || 0;


# TODO - Set up Variables!


my %authentications;
my %failed_authentications;


#----------------------
# Parse the log
#----------------------
while (my $line = <STDIN>) {
	chomp($line);
	
	if($line =~ /.*Successfully authenticated user \[(.*)\] from address\/host \[(.*)\].*/g) {
		$authentications{$1}{$2}++;
	}	
	
}

#--------------------------------
# Print authentication results  
#--------------------------------
if((length keys %authentications) > 0) {
	print "Successful Authentications:\n";
	foreach my $user (keys %authentications) {
		my $total = 0;
	
		my $tmp = $authentications{$user};
		foreach my $domain (keys %{$tmp}) {
			$total += $authentications{$user}{$domain};		
		}		
		print "\t${user} (${total} time(s))\n" if $detail > 0;
		
		if( $detail > 7 ) {
			foreach my $domain (keys %{$tmp}) {
				print "\t\tfrom [${domain}] (${authentications{$user}{$domain}} times(s))\n"			
			}			
		}
	}
}